services:
  app:
    build: .
    tty: true
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/code
    networks:
      - api_bot

networks:
  api_bot:
    driver: bridge
