services:
  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    networks:
      - api_bot

  bot:
    build: .
    tty: true
    env_file:
      - .env
    command: sh -c "python manage.py runbot"
    volumes:
      - .:/code
    networks:
      - api_bot

networks:
  api_bot:
    driver: bridge