# Generated by Django 5.1.5 on 2025-01-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelisteduser',
            options={'verbose_name': 'Белый лист', 'verbose_name_plural': 'Белый лист'},
        ),
    ]
